#!/bin/sh
DEVICE=/dev/ttyUSB0

set_led() {
  local VALUE=$(( ($1 * 5) / 31 ))
  local i=1
  while [ $i -le 5 ]; do
    if [ $i -le $VALUE ]; then
      echo 1 > "/sys/class/leds/blue:signal$i/brightness" 2>/dev/null
    else
      echo 0 > "/sys/class/leds/blue:signal$i/brightness" 2>/dev/null
    fi
    i=$((i+1))
  done
}

[ ! -e "$DEVICE" ] && exit 0

CSQ=$(sms_tool -d $DEVICE at AT+CSQ | awk -F'[,\ ]' '/^\+CSQ/ {print $2}')
[ -z "$CSQ" ] && exit 0

set_led $CSQ
